// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: protobuf/proto/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deployment
type ContainerState int32

const (
	ContainerState_CONTAINER_STATE_UNSPECIFIED ContainerState = 0
	ContainerState_RUNNING                     ContainerState = 1
	ContainerState_WAITING                     ContainerState = 2
	ContainerState_EXITED                      ContainerState = 3
	ContainerState_REMOVED                     ContainerState = 4
)

// Enum value maps for ContainerState.
var (
	ContainerState_name = map[int32]string{
		0: "CONTAINER_STATE_UNSPECIFIED",
		1: "RUNNING",
		2: "WAITING",
		3: "EXITED",
		4: "REMOVED",
	}
	ContainerState_value = map[string]int32{
		"CONTAINER_STATE_UNSPECIFIED": 0,
		"RUNNING":                     1,
		"WAITING":                     2,
		"EXITED":                      3,
		"REMOVED":                     4,
	}
)

func (x ContainerState) Enum() *ContainerState {
	p := new(ContainerState)
	*p = x
	return p
}

func (x ContainerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerState) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_common_proto_enumTypes[0].Descriptor()
}

func (ContainerState) Type() protoreflect.EnumType {
	return &file_protobuf_proto_common_proto_enumTypes[0]
}

func (x ContainerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerState.Descriptor instead.
func (ContainerState) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{0}
}

type DeploymentStatus int32

const (
	DeploymentStatus_DEPLOYMENT_STATUS_UNSPECIFIED DeploymentStatus = 0
	DeploymentStatus_PREPARING                     DeploymentStatus = 1
	DeploymentStatus_IN_PROGRESS                   DeploymentStatus = 2
	DeploymentStatus_SUCCESSFUL                    DeploymentStatus = 3
	DeploymentStatus_FAILED                        DeploymentStatus = 4
	DeploymentStatus_OBSOLETE                      DeploymentStatus = 5
	DeploymentStatus_DOWNGRADED                    DeploymentStatus = 6
)

// Enum value maps for DeploymentStatus.
var (
	DeploymentStatus_name = map[int32]string{
		0: "DEPLOYMENT_STATUS_UNSPECIFIED",
		1: "PREPARING",
		2: "IN_PROGRESS",
		3: "SUCCESSFUL",
		4: "FAILED",
		5: "OBSOLETE",
		6: "DOWNGRADED",
	}
	DeploymentStatus_value = map[string]int32{
		"DEPLOYMENT_STATUS_UNSPECIFIED": 0,
		"PREPARING":                     1,
		"IN_PROGRESS":                   2,
		"SUCCESSFUL":                    3,
		"FAILED":                        4,
		"OBSOLETE":                      5,
		"DOWNGRADED":                    6,
	}
)

func (x DeploymentStatus) Enum() *DeploymentStatus {
	p := new(DeploymentStatus)
	*p = x
	return p
}

func (x DeploymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_common_proto_enumTypes[1].Descriptor()
}

func (DeploymentStatus) Type() protoreflect.EnumType {
	return &file_protobuf_proto_common_proto_enumTypes[1]
}

func (x DeploymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentStatus.Descriptor instead.
func (DeploymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{1}
}

type NetworkMode int32

const (
	NetworkMode_NETWORK_MODE_UNSPECIFIED NetworkMode = 0
	NetworkMode_BRIDGE                   NetworkMode = 1
	NetworkMode_HOST                     NetworkMode = 2
	NetworkMode_NONE                     NetworkMode = 6
)

// Enum value maps for NetworkMode.
var (
	NetworkMode_name = map[int32]string{
		0: "NETWORK_MODE_UNSPECIFIED",
		1: "BRIDGE",
		2: "HOST",
		6: "NONE",
	}
	NetworkMode_value = map[string]int32{
		"NETWORK_MODE_UNSPECIFIED": 0,
		"BRIDGE":                   1,
		"HOST":                     2,
		"NONE":                     6,
	}
)

func (x NetworkMode) Enum() *NetworkMode {
	p := new(NetworkMode)
	*p = x
	return p
}

func (x NetworkMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkMode) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_common_proto_enumTypes[2].Descriptor()
}

func (NetworkMode) Type() protoreflect.EnumType {
	return &file_protobuf_proto_common_proto_enumTypes[2]
}

func (x NetworkMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkMode.Descriptor instead.
func (NetworkMode) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{2}
}

type RestartPolicy int32

const (
	RestartPolicy_POLICY_UNSPECIFIED RestartPolicy = 0
	RestartPolicy_UNDEFINED          RestartPolicy = 1
	RestartPolicy_NO                 RestartPolicy = 2
	RestartPolicy_ON_FAILURE         RestartPolicy = 3
	RestartPolicy_ALWAYS             RestartPolicy = 4
	RestartPolicy_UNLESS_STOPPED     RestartPolicy = 5
)

// Enum value maps for RestartPolicy.
var (
	RestartPolicy_name = map[int32]string{
		0: "POLICY_UNSPECIFIED",
		1: "UNDEFINED",
		2: "NO",
		3: "ON_FAILURE",
		4: "ALWAYS",
		5: "UNLESS_STOPPED",
	}
	RestartPolicy_value = map[string]int32{
		"POLICY_UNSPECIFIED": 0,
		"UNDEFINED":          1,
		"NO":                 2,
		"ON_FAILURE":         3,
		"ALWAYS":             4,
		"UNLESS_STOPPED":     5,
	}
)

func (x RestartPolicy) Enum() *RestartPolicy {
	p := new(RestartPolicy)
	*p = x
	return p
}

func (x RestartPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_common_proto_enumTypes[3].Descriptor()
}

func (RestartPolicy) Type() protoreflect.EnumType {
	return &file_protobuf_proto_common_proto_enumTypes[3]
}

func (x RestartPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartPolicy.Descriptor instead.
func (RestartPolicy) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{3}
}

type DeploymentStrategy int32

const (
	DeploymentStrategy_DEPLOYMENT_STRATEGY_UNSPECIFIED DeploymentStrategy = 0
	DeploymentStrategy_RECREATE                        DeploymentStrategy = 1
	DeploymentStrategy_ROLLING_UPDATE                  DeploymentStrategy = 2
)

// Enum value maps for DeploymentStrategy.
var (
	DeploymentStrategy_name = map[int32]string{
		0: "DEPLOYMENT_STRATEGY_UNSPECIFIED",
		1: "RECREATE",
		2: "ROLLING_UPDATE",
	}
	DeploymentStrategy_value = map[string]int32{
		"DEPLOYMENT_STRATEGY_UNSPECIFIED": 0,
		"RECREATE":                        1,
		"ROLLING_UPDATE":                  2,
	}
)

func (x DeploymentStrategy) Enum() *DeploymentStrategy {
	p := new(DeploymentStrategy)
	*p = x
	return p
}

func (x DeploymentStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_common_proto_enumTypes[4].Descriptor()
}

func (DeploymentStrategy) Type() protoreflect.EnumType {
	return &file_protobuf_proto_common_proto_enumTypes[4]
}

func (x DeploymentStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentStrategy.Descriptor instead.
func (DeploymentStrategy) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{4}
}

type VolumeType int32

const (
	VolumeType_VOLUME_TYPE_UNSPECIFIED VolumeType = 0
	VolumeType_RO                      VolumeType = 1
	VolumeType_RWO                     VolumeType = 2
	VolumeType_RWX                     VolumeType = 3
	VolumeType_MEM                     VolumeType = 4
	VolumeType_TMP                     VolumeType = 5
)

// Enum value maps for VolumeType.
var (
	VolumeType_name = map[int32]string{
		0: "VOLUME_TYPE_UNSPECIFIED",
		1: "RO",
		2: "RWO",
		3: "RWX",
		4: "MEM",
		5: "TMP",
	}
	VolumeType_value = map[string]int32{
		"VOLUME_TYPE_UNSPECIFIED": 0,
		"RO":                      1,
		"RWO":                     2,
		"RWX":                     3,
		"MEM":                     4,
		"TMP":                     5,
	}
)

func (x VolumeType) Enum() *VolumeType {
	p := new(VolumeType)
	*p = x
	return p
}

func (x VolumeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VolumeType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_common_proto_enumTypes[5].Descriptor()
}

func (VolumeType) Type() protoreflect.EnumType {
	return &file_protobuf_proto_common_proto_enumTypes[5]
}

func (x VolumeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VolumeType.Descriptor instead.
func (VolumeType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{5}
}

type DriverType int32

const (
	DriverType_DRIVER_TYPE_UNSPECIFIED DriverType = 0
	DriverType_NODE_DEFAULT            DriverType = 1
	DriverType_DRIVER_TYPE_NONE        DriverType = 2
	DriverType_GCPLOGS                 DriverType = 3
	DriverType_LOCAL                   DriverType = 4
	DriverType_JSON_FILE               DriverType = 5
	DriverType_SYSLOG                  DriverType = 6
	DriverType_JOURNALD                DriverType = 7
	DriverType_GELF                    DriverType = 8
	DriverType_FLUENTD                 DriverType = 9
	DriverType_AWSLOGS                 DriverType = 10
	DriverType_SPLUNK                  DriverType = 11
	DriverType_ETWLOGS                 DriverType = 12
	DriverType_LOGENTRIES              DriverType = 13
)

// Enum value maps for DriverType.
var (
	DriverType_name = map[int32]string{
		0:  "DRIVER_TYPE_UNSPECIFIED",
		1:  "NODE_DEFAULT",
		2:  "DRIVER_TYPE_NONE",
		3:  "GCPLOGS",
		4:  "LOCAL",
		5:  "JSON_FILE",
		6:  "SYSLOG",
		7:  "JOURNALD",
		8:  "GELF",
		9:  "FLUENTD",
		10: "AWSLOGS",
		11: "SPLUNK",
		12: "ETWLOGS",
		13: "LOGENTRIES",
	}
	DriverType_value = map[string]int32{
		"DRIVER_TYPE_UNSPECIFIED": 0,
		"NODE_DEFAULT":            1,
		"DRIVER_TYPE_NONE":        2,
		"GCPLOGS":                 3,
		"LOCAL":                   4,
		"JSON_FILE":               5,
		"SYSLOG":                  6,
		"JOURNALD":                7,
		"GELF":                    8,
		"FLUENTD":                 9,
		"AWSLOGS":                 10,
		"SPLUNK":                  11,
		"ETWLOGS":                 12,
		"LOGENTRIES":              13,
	}
)

func (x DriverType) Enum() *DriverType {
	p := new(DriverType)
	*p = x
	return p
}

func (x DriverType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_common_proto_enumTypes[6].Descriptor()
}

func (DriverType) Type() protoreflect.EnumType {
	return &file_protobuf_proto_common_proto_enumTypes[6]
}

func (x DriverType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverType.Descriptor instead.
func (DriverType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{6}
}

type ExposeStrategy int32

const (
	ExposeStrategy_EXPOSE_STRATEGY_UNSPECIFIED ExposeStrategy = 0
	ExposeStrategy_NONE_ES                     ExposeStrategy = 1
	ExposeStrategy_EXPOSE                      ExposeStrategy = 2
	ExposeStrategy_EXPOSE_WITH_TLS             ExposeStrategy = 3
)

// Enum value maps for ExposeStrategy.
var (
	ExposeStrategy_name = map[int32]string{
		0: "EXPOSE_STRATEGY_UNSPECIFIED",
		1: "NONE_ES",
		2: "EXPOSE",
		3: "EXPOSE_WITH_TLS",
	}
	ExposeStrategy_value = map[string]int32{
		"EXPOSE_STRATEGY_UNSPECIFIED": 0,
		"NONE_ES":                     1,
		"EXPOSE":                      2,
		"EXPOSE_WITH_TLS":             3,
	}
)

func (x ExposeStrategy) Enum() *ExposeStrategy {
	p := new(ExposeStrategy)
	*p = x
	return p
}

func (x ExposeStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExposeStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_common_proto_enumTypes[7].Descriptor()
}

func (ExposeStrategy) Type() protoreflect.EnumType {
	return &file_protobuf_proto_common_proto_enumTypes[7]
}

func (x ExposeStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExposeStrategy.Descriptor instead.
func (ExposeStrategy) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{7}
}

type ContainerOperation int32

const (
	ContainerOperation_CONTAINER_OPERATION_UNSPECIFIED ContainerOperation = 0
	ContainerOperation_START_CONTAINER                 ContainerOperation = 1
	ContainerOperation_STOP_CONTAINER                  ContainerOperation = 2
	ContainerOperation_RESTART_CONTAINER               ContainerOperation = 3
)

// Enum value maps for ContainerOperation.
var (
	ContainerOperation_name = map[int32]string{
		0: "CONTAINER_OPERATION_UNSPECIFIED",
		1: "START_CONTAINER",
		2: "STOP_CONTAINER",
		3: "RESTART_CONTAINER",
	}
	ContainerOperation_value = map[string]int32{
		"CONTAINER_OPERATION_UNSPECIFIED": 0,
		"START_CONTAINER":                 1,
		"STOP_CONTAINER":                  2,
		"RESTART_CONTAINER":               3,
	}
)

func (x ContainerOperation) Enum() *ContainerOperation {
	p := new(ContainerOperation)
	*p = x
	return p
}

func (x ContainerOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_common_proto_enumTypes[8].Descriptor()
}

func (ContainerOperation) Type() protoreflect.EnumType {
	return &file_protobuf_proto_common_proto_enumTypes[8]
}

func (x ContainerOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerOperation.Descriptor instead.
func (ContainerOperation) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{8}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{0}
}

type InstanceDeploymentItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId string         `protobuf:"bytes,100,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	State      ContainerState `protobuf:"varint,101,opt,name=state,proto3,enum=common.ContainerState" json:"state,omitempty"`
	Reason     string         `protobuf:"bytes,102,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *InstanceDeploymentItem) Reset() {
	*x = InstanceDeploymentItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstanceDeploymentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceDeploymentItem) ProtoMessage() {}

func (x *InstanceDeploymentItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceDeploymentItem.ProtoReflect.Descriptor instead.
func (*InstanceDeploymentItem) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *InstanceDeploymentItem) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceDeploymentItem) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CONTAINER_STATE_UNSPECIFIED
}

func (x *InstanceDeploymentItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeploymentStatusMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*DeploymentStatusMessage_Instance
	//	*DeploymentStatusMessage_DeploymentStatus
	Data isDeploymentStatusMessage_Data `protobuf_oneof:"data"`
	Log  []string                       `protobuf:"bytes,1000,rep,name=log,proto3" json:"log,omitempty"`
}

func (x *DeploymentStatusMessage) Reset() {
	*x = DeploymentStatusMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploymentStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentStatusMessage) ProtoMessage() {}

func (x *DeploymentStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentStatusMessage.ProtoReflect.Descriptor instead.
func (*DeploymentStatusMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{2}
}

func (m *DeploymentStatusMessage) GetData() isDeploymentStatusMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *DeploymentStatusMessage) GetInstance() *InstanceDeploymentItem {
	if x, ok := x.GetData().(*DeploymentStatusMessage_Instance); ok {
		return x.Instance
	}
	return nil
}

func (x *DeploymentStatusMessage) GetDeploymentStatus() DeploymentStatus {
	if x, ok := x.GetData().(*DeploymentStatusMessage_DeploymentStatus); ok {
		return x.DeploymentStatus
	}
	return DeploymentStatus_DEPLOYMENT_STATUS_UNSPECIFIED
}

func (x *DeploymentStatusMessage) GetLog() []string {
	if x != nil {
		return x.Log
	}
	return nil
}

type isDeploymentStatusMessage_Data interface {
	isDeploymentStatusMessage_Data()
}

type DeploymentStatusMessage_Instance struct {
	Instance *InstanceDeploymentItem `protobuf:"bytes,200,opt,name=instance,proto3,oneof"`
}

type DeploymentStatusMessage_DeploymentStatus struct {
	DeploymentStatus DeploymentStatus `protobuf:"varint,201,opt,name=deploymentStatus,proto3,enum=common.DeploymentStatus,oneof"`
}

func (*DeploymentStatusMessage_Instance) isDeploymentStatusMessage_Data() {}

func (*DeploymentStatusMessage_DeploymentStatus) isDeploymentStatusMessage_Data() {}

type ContainerStateItemPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Internal int32 `protobuf:"varint,100,opt,name=internal,proto3" json:"internal,omitempty"`
	External int32 `protobuf:"varint,101,opt,name=external,proto3" json:"external,omitempty"`
}

func (x *ContainerStateItemPort) Reset() {
	*x = ContainerStateItemPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerStateItemPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStateItemPort) ProtoMessage() {}

func (x *ContainerStateItemPort) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStateItemPort.ProtoReflect.Descriptor instead.
func (*ContainerStateItemPort) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerStateItemPort) GetInternal() int32 {
	if x != nil {
		return x.Internal
	}
	return 0
}

func (x *ContainerStateItemPort) GetExternal() int32 {
	if x != nil {
		return x.External
	}
	return 0
}

type ContainerStateListMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix *string               `protobuf:"bytes,100,opt,name=prefix,proto3,oneof" json:"prefix,omitempty"`
	Data   []*ContainerStateItem `protobuf:"bytes,1000,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ContainerStateListMessage) Reset() {
	*x = ContainerStateListMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerStateListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStateListMessage) ProtoMessage() {}

func (x *ContainerStateListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStateListMessage.ProtoReflect.Descriptor instead.
func (*ContainerStateListMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerStateListMessage) GetPrefix() string {
	if x != nil && x.Prefix != nil {
		return *x.Prefix
	}
	return ""
}

func (x *ContainerStateListMessage) GetData() []*ContainerStateItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type ContainerStateItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        *ContainerIdentifier   `protobuf:"bytes,100,opt,name=id,proto3" json:"id,omitempty"`
	Command   string                 `protobuf:"bytes,101,opt,name=command,proto3" json:"command,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,102,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// The 'State' of the container (Created, Running, etc)
	State ContainerState `protobuf:"varint,103,opt,name=state,proto3,enum=common.ContainerState" json:"state,omitempty"`
	// The 'reason' behind 'state'.
	Reason string `protobuf:"bytes,107,opt,name=reason,proto3" json:"reason,omitempty"`
	// The 'Status' of the container ("Created 1min ago", "Exited with code 123",
	// etc). Unused but left here for reverse compatibility with the legacy
	// version.
	Status    string                    `protobuf:"bytes,104,opt,name=status,proto3" json:"status,omitempty"`
	ImageName string                    `protobuf:"bytes,105,opt,name=imageName,proto3" json:"imageName,omitempty"`
	ImageTag  string                    `protobuf:"bytes,106,opt,name=imageTag,proto3" json:"imageTag,omitempty"`
	Ports     []*ContainerStateItemPort `protobuf:"bytes,1000,rep,name=ports,proto3" json:"ports,omitempty"`
	Labels    map[string]string         `protobuf:"bytes,1001,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ContainerStateItem) Reset() {
	*x = ContainerStateItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerStateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStateItem) ProtoMessage() {}

func (x *ContainerStateItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStateItem.ProtoReflect.Descriptor instead.
func (*ContainerStateItem) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerStateItem) GetId() *ContainerIdentifier {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ContainerStateItem) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ContainerStateItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ContainerStateItem) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CONTAINER_STATE_UNSPECIFIED
}

func (x *ContainerStateItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ContainerStateItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerStateItem) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ContainerStateItem) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *ContainerStateItem) GetPorts() []*ContainerStateItemPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerStateItem) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ContainerLogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log string `protobuf:"bytes,100,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *ContainerLogMessage) Reset() {
	*x = ContainerLogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerLogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogMessage) ProtoMessage() {}

func (x *ContainerLogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogMessage.ProtoReflect.Descriptor instead.
func (*ContainerLogMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerLogMessage) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type ContainerInspectMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix     string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Inspection string `protobuf:"bytes,3,opt,name=inspection,proto3" json:"inspection,omitempty"`
}

func (x *ContainerInspectMessage) Reset() {
	*x = ContainerInspectMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerInspectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInspectMessage) ProtoMessage() {}

func (x *ContainerInspectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInspectMessage.ProtoReflect.Descriptor instead.
func (*ContainerInspectMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerInspectMessage) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ContainerInspectMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInspectMessage) GetInspection() string {
	if x != nil {
		return x.Inspection
	}
	return ""
}

type Routing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain      *string `protobuf:"bytes,100,opt,name=domain,proto3,oneof" json:"domain,omitempty"`
	Path        *string `protobuf:"bytes,101,opt,name=path,proto3,oneof" json:"path,omitempty"`
	StripPath   *bool   `protobuf:"varint,102,opt,name=stripPath,proto3,oneof" json:"stripPath,omitempty"`
	UploadLimit *string `protobuf:"bytes,103,opt,name=uploadLimit,proto3,oneof" json:"uploadLimit,omitempty"`
	Port        *uint32 `protobuf:"varint,104,opt,name=port,proto3,oneof" json:"port,omitempty"`
}

func (x *Routing) Reset() {
	*x = Routing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Routing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Routing) ProtoMessage() {}

func (x *Routing) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Routing.ProtoReflect.Descriptor instead.
func (*Routing) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{8}
}

func (x *Routing) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *Routing) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *Routing) GetStripPath() bool {
	if x != nil && x.StripPath != nil {
		return *x.StripPath
	}
	return false
}

func (x *Routing) GetUploadLimit() string {
	if x != nil && x.UploadLimit != nil {
		return *x.UploadLimit
	}
	return ""
}

func (x *Routing) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

type ConfigContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image     string `protobuf:"bytes,100,opt,name=image,proto3" json:"image,omitempty"`
	Volume    string `protobuf:"bytes,101,opt,name=volume,proto3" json:"volume,omitempty"`
	Path      string `protobuf:"bytes,102,opt,name=path,proto3" json:"path,omitempty"`
	KeepFiles bool   `protobuf:"varint,103,opt,name=keepFiles,proto3" json:"keepFiles,omitempty"`
}

func (x *ConfigContainer) Reset() {
	*x = ConfigContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigContainer) ProtoMessage() {}

func (x *ConfigContainer) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigContainer.ProtoReflect.Descriptor instead.
func (*ConfigContainer) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ConfigContainer) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *ConfigContainer) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigContainer) GetKeepFiles() bool {
	if x != nil {
		return x.KeepFiles
	}
	return false
}

type HealthCheckConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port           *int32  `protobuf:"varint,100,opt,name=port,proto3,oneof" json:"port,omitempty"`
	LivenessProbe  *string `protobuf:"bytes,101,opt,name=livenessProbe,proto3,oneof" json:"livenessProbe,omitempty"`
	ReadinessProbe *string `protobuf:"bytes,102,opt,name=readinessProbe,proto3,oneof" json:"readinessProbe,omitempty"`
	StartupProbe   *string `protobuf:"bytes,103,opt,name=startupProbe,proto3,oneof" json:"startupProbe,omitempty"`
}

func (x *HealthCheckConfig) Reset() {
	*x = HealthCheckConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckConfig) ProtoMessage() {}

func (x *HealthCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckConfig.ProtoReflect.Descriptor instead.
func (*HealthCheckConfig) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckConfig) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *HealthCheckConfig) GetLivenessProbe() string {
	if x != nil && x.LivenessProbe != nil {
		return *x.LivenessProbe
	}
	return ""
}

func (x *HealthCheckConfig) GetReadinessProbe() string {
	if x != nil && x.ReadinessProbe != nil {
		return *x.ReadinessProbe
	}
	return ""
}

func (x *HealthCheckConfig) GetStartupProbe() string {
	if x != nil && x.StartupProbe != nil {
		return *x.StartupProbe
	}
	return ""
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu    *string `protobuf:"bytes,100,opt,name=cpu,proto3,oneof" json:"cpu,omitempty"`
	Memory *string `protobuf:"bytes,101,opt,name=memory,proto3,oneof" json:"memory,omitempty"`
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{11}
}

func (x *Resource) GetCpu() string {
	if x != nil && x.Cpu != nil {
		return *x.Cpu
	}
	return ""
}

func (x *Resource) GetMemory() string {
	if x != nil && x.Memory != nil {
		return *x.Memory
	}
	return ""
}

type ResourceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limits   *Resource `protobuf:"bytes,100,opt,name=limits,proto3,oneof" json:"limits,omitempty"`
	Requests *Resource `protobuf:"bytes,101,opt,name=requests,proto3,oneof" json:"requests,omitempty"`
}

func (x *ResourceConfig) Reset() {
	*x = ResourceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig) ProtoMessage() {}

func (x *ResourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig.ProtoReflect.Descriptor instead.
func (*ResourceConfig) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{12}
}

func (x *ResourceConfig) GetLimits() *Resource {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *ResourceConfig) GetRequests() *Resource {
	if x != nil {
		return x.Requests
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,100,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,101,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{13}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix    string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Name      string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey string   `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	HasKeys   bool     `protobuf:"varint,4,opt,name=hasKeys,proto3" json:"hasKeys,omitempty"`
	Keys      []string `protobuf:"bytes,5,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{14}
}

func (x *ListSecretsResponse) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListSecretsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListSecretsResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ListSecretsResponse) GetHasKeys() bool {
	if x != nil {
		return x.HasKeys
	}
	return false
}

func (x *ListSecretsResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type UniqueKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,100,opt,name=id,proto3" json:"id,omitempty"`
	Key string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *UniqueKey) Reset() {
	*x = UniqueKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueKey) ProtoMessage() {}

func (x *UniqueKey) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueKey.ProtoReflect.Descriptor instead.
func (*UniqueKey) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{15}
}

func (x *UniqueKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UniqueKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ContainerIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ContainerIdentifier) Reset() {
	*x = ContainerIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerIdentifier) ProtoMessage() {}

func (x *ContainerIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerIdentifier.ProtoReflect.Descriptor instead.
func (*ContainerIdentifier) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{16}
}

func (x *ContainerIdentifier) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ContainerIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ContainerCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Container *ContainerIdentifier `protobuf:"bytes,100,opt,name=container,proto3" json:"container,omitempty"`
	Operation ContainerOperation   `protobuf:"varint,101,opt,name=operation,proto3,enum=common.ContainerOperation" json:"operation,omitempty"`
}

func (x *ContainerCommandRequest) Reset() {
	*x = ContainerCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCommandRequest) ProtoMessage() {}

func (x *ContainerCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCommandRequest.ProtoReflect.Descriptor instead.
func (*ContainerCommandRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{17}
}

func (x *ContainerCommandRequest) GetContainer() *ContainerIdentifier {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *ContainerCommandRequest) GetOperation() ContainerOperation {
	if x != nil {
		return x.Operation
	}
	return ContainerOperation_CONTAINER_OPERATION_UNSPECIFIED
}

type DeleteContainersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Target:
	//
	//	*DeleteContainersRequest_Container
	//	*DeleteContainersRequest_Prefix
	Target isDeleteContainersRequest_Target `protobuf_oneof:"target"`
}

func (x *DeleteContainersRequest) Reset() {
	*x = DeleteContainersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_common_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainersRequest) ProtoMessage() {}

func (x *DeleteContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_common_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainersRequest.ProtoReflect.Descriptor instead.
func (*DeleteContainersRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_common_proto_rawDescGZIP(), []int{18}
}

func (m *DeleteContainersRequest) GetTarget() isDeleteContainersRequest_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (x *DeleteContainersRequest) GetContainer() *ContainerIdentifier {
	if x, ok := x.GetTarget().(*DeleteContainersRequest_Container); ok {
		return x.Container
	}
	return nil
}

func (x *DeleteContainersRequest) GetPrefix() string {
	if x, ok := x.GetTarget().(*DeleteContainersRequest_Prefix); ok {
		return x.Prefix
	}
	return ""
}

type isDeleteContainersRequest_Target interface {
	isDeleteContainersRequest_Target()
}

type DeleteContainersRequest_Container struct {
	Container *ContainerIdentifier `protobuf:"bytes,201,opt,name=container,proto3,oneof"`
}

type DeleteContainersRequest_Prefix struct {
	Prefix string `protobuf:"bytes,202,opt,name=prefix,proto3,oneof"`
}

func (*DeleteContainersRequest_Container) isDeleteContainersRequest_Target() {}

func (*DeleteContainersRequest_Prefix) isDeleteContainersRequest_Target() {}

var File_protobuf_proto_common_proto protoreflect.FileDescriptor

var file_protobuf_proto_common_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x7e, 0x0a, 0x16, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x66, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0xbc, 0x01, 0x0a, 0x17, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0xc8, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x48, 0x00,
	0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x64, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0xc9,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48,
	0x00, 0x52, 0x10, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x11, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0xe8, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x50,
	0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x18, 0x64, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x18, 0x65, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x22, 0x74, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a,
	0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0xe8, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0xe0, 0x03, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2b, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2c,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x67, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x6b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x68,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x69, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x18, 0x6a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x12, 0x35, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18,
	0xe8, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x3f, 0x0a,
	0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0xe9, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x1a, 0x39,
	0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x27, 0x0a, 0x13, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c,
	0x6f, 0x67, 0x22, 0x65, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49,
	0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73,
	0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x6e, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xdd, 0x01, 0x0a, 0x07, 0x52, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18,
	0x64, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x73,
	0x74, 0x72, 0x69, 0x70, 0x50, 0x61, 0x74, 0x68, 0x18, 0x66, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02,
	0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x70, 0x50, 0x61, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12, 0x25,
	0x0a, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x67, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x68, 0x20,
	0x01, 0x28, 0x0d, 0x48, 0x04, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x70, 0x50, 0x61, 0x74, 0x68,
	0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x71, 0x0a, 0x0f, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x65, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x66, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1c,
	0x0a, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x67, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xec, 0x01, 0x0a,
	0x11, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x64, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x0d, 0x6c,
	0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x18, 0x65, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0d, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x0e, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x18, 0x66, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02,
	0x52, 0x0e, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x18, 0x67, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0c, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x65,
	0x73, 0x73, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x72, 0x65, 0x61, 0x64,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x22, 0x51, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x64,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x63, 0x70, 0x75, 0x88, 0x01, 0x01, 0x12, 0x1b,
	0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f,
	0x63, 0x70, 0x75, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x22, 0x8a,
	0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x64, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x88, 0x01, 0x01,
	0x12, 0x31, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x65, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x48, 0x01, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x32, 0x0a, 0x08, 0x4b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x64,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x8d, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22,
	0x2d, 0x0a, 0x09, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x41,
	0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x8e, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a,
	0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x09, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x7c, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a,
	0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0xc9, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x48, 0x00,
	0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0xca, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x42, 0x08, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x2a, 0x64, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0a, 0x0a,
	0x06, 0x45, 0x58, 0x49, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x4d,
	0x4f, 0x56, 0x45, 0x44, 0x10, 0x04, 0x2a, 0x8f, 0x01, 0x0a, 0x10, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x1d, 0x44,
	0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0f, 0x0a,
	0x0b, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0e,
	0x0a, 0x0a, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x46, 0x55, 0x4c, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x42,
	0x53, 0x4f, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x4f, 0x57, 0x4e,
	0x47, 0x52, 0x41, 0x44, 0x45, 0x44, 0x10, 0x06, 0x2a, 0x4b, 0x0a, 0x0b, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x4e, 0x45, 0x54, 0x57, 0x4f,
	0x52, 0x4b, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x52, 0x49, 0x44, 0x47, 0x45, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x06, 0x2a, 0x6e, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x01, 0x12, 0x06, 0x0a,
	0x02, 0x4e, 0x4f, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x4e, 0x5f, 0x46, 0x41, 0x49, 0x4c,
	0x55, 0x52, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x4c, 0x57, 0x41, 0x59, 0x53, 0x10,
	0x04, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4c, 0x45, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x4f, 0x50,
	0x50, 0x45, 0x44, 0x10, 0x05, 0x2a, 0x5b, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x23, 0x0a, 0x1f, 0x44,
	0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x52, 0x41, 0x54, 0x45,
	0x47, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x12,
	0x0a, 0x0e, 0x52, 0x4f, 0x4c, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45,
	0x10, 0x02, 0x2a, 0x55, 0x0a, 0x0a, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x17, 0x56, 0x4f, 0x4c, 0x55, 0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a,
	0x02, 0x52, 0x4f, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x57, 0x4f, 0x10, 0x02, 0x12, 0x07,
	0x0a, 0x03, 0x52, 0x57, 0x58, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x45, 0x4d, 0x10, 0x04,
	0x12, 0x07, 0x0a, 0x03, 0x54, 0x4d, 0x50, 0x10, 0x05, 0x2a, 0xdf, 0x01, 0x0a, 0x0a, 0x44, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x52, 0x49, 0x56,
	0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x44, 0x45,
	0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x52, 0x49, 0x56, 0x45,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x47, 0x43, 0x50, 0x4c, 0x4f, 0x47, 0x53, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f,
	0x43, 0x41, 0x4c, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x4a, 0x53, 0x4f, 0x4e, 0x5f, 0x46, 0x49,
	0x4c, 0x45, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59, 0x53, 0x4c, 0x4f, 0x47, 0x10, 0x06,
	0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x4f, 0x55, 0x52, 0x4e, 0x41, 0x4c, 0x44, 0x10, 0x07, 0x12, 0x08,
	0x0a, 0x04, 0x47, 0x45, 0x4c, 0x46, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4c, 0x55, 0x45,
	0x4e, 0x54, 0x44, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x57, 0x53, 0x4c, 0x4f, 0x47, 0x53,
	0x10, 0x0a, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x50, 0x4c, 0x55, 0x4e, 0x4b, 0x10, 0x0b, 0x12, 0x0b,
	0x0a, 0x07, 0x45, 0x54, 0x57, 0x4c, 0x4f, 0x47, 0x53, 0x10, 0x0c, 0x12, 0x0e, 0x0a, 0x0a, 0x4c,
	0x4f, 0x47, 0x45, 0x4e, 0x54, 0x52, 0x49, 0x45, 0x53, 0x10, 0x0d, 0x2a, 0x5f, 0x0a, 0x0e, 0x45,
	0x78, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x1f, 0x0a,
	0x1b, 0x45, 0x58, 0x50, 0x4f, 0x53, 0x45, 0x5f, 0x53, 0x54, 0x52, 0x41, 0x54, 0x45, 0x47, 0x59,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x4e, 0x4f, 0x4e, 0x45, 0x5f, 0x45, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x45,
	0x58, 0x50, 0x4f, 0x53, 0x45, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x58, 0x50, 0x4f, 0x53,
	0x45, 0x5f, 0x57, 0x49, 0x54, 0x48, 0x5f, 0x54, 0x4c, 0x53, 0x10, 0x03, 0x2a, 0x79, 0x0a, 0x12,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x1f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f,
	0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x52, 0x54,
	0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e,
	0x53, 0x54, 0x4f, 0x50, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x10, 0x02,
	0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54,
	0x41, 0x49, 0x4e, 0x45, 0x52, 0x10, 0x03, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x79, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x69,
	0x6f, 0x2f, 0x64, 0x79, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_proto_common_proto_rawDescOnce sync.Once
	file_protobuf_proto_common_proto_rawDescData = file_protobuf_proto_common_proto_rawDesc
)

func file_protobuf_proto_common_proto_rawDescGZIP() []byte {
	file_protobuf_proto_common_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_common_proto_rawDescData)
	})
	return file_protobuf_proto_common_proto_rawDescData
}

var file_protobuf_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_protobuf_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_protobuf_proto_common_proto_goTypes = []interface{}{
	(ContainerState)(0),               // 0: common.ContainerState
	(DeploymentStatus)(0),             // 1: common.DeploymentStatus
	(NetworkMode)(0),                  // 2: common.NetworkMode
	(RestartPolicy)(0),                // 3: common.RestartPolicy
	(DeploymentStrategy)(0),           // 4: common.DeploymentStrategy
	(VolumeType)(0),                   // 5: common.VolumeType
	(DriverType)(0),                   // 6: common.DriverType
	(ExposeStrategy)(0),               // 7: common.ExposeStrategy
	(ContainerOperation)(0),           // 8: common.ContainerOperation
	(*Empty)(nil),                     // 9: common.Empty
	(*InstanceDeploymentItem)(nil),    // 10: common.InstanceDeploymentItem
	(*DeploymentStatusMessage)(nil),   // 11: common.DeploymentStatusMessage
	(*ContainerStateItemPort)(nil),    // 12: common.ContainerStateItemPort
	(*ContainerStateListMessage)(nil), // 13: common.ContainerStateListMessage
	(*ContainerStateItem)(nil),        // 14: common.ContainerStateItem
	(*ContainerLogMessage)(nil),       // 15: common.ContainerLogMessage
	(*ContainerInspectMessage)(nil),   // 16: common.ContainerInspectMessage
	(*Routing)(nil),                   // 17: common.Routing
	(*ConfigContainer)(nil),           // 18: common.ConfigContainer
	(*HealthCheckConfig)(nil),         // 19: common.HealthCheckConfig
	(*Resource)(nil),                  // 20: common.Resource
	(*ResourceConfig)(nil),            // 21: common.ResourceConfig
	(*KeyValue)(nil),                  // 22: common.KeyValue
	(*ListSecretsResponse)(nil),       // 23: common.ListSecretsResponse
	(*UniqueKey)(nil),                 // 24: common.UniqueKey
	(*ContainerIdentifier)(nil),       // 25: common.ContainerIdentifier
	(*ContainerCommandRequest)(nil),   // 26: common.ContainerCommandRequest
	(*DeleteContainersRequest)(nil),   // 27: common.DeleteContainersRequest
	nil,                               // 28: common.ContainerStateItem.LabelsEntry
	(*timestamppb.Timestamp)(nil),     // 29: google.protobuf.Timestamp
}
var file_protobuf_proto_common_proto_depIdxs = []int32{
	0,  // 0: common.InstanceDeploymentItem.state:type_name -> common.ContainerState
	10, // 1: common.DeploymentStatusMessage.instance:type_name -> common.InstanceDeploymentItem
	1,  // 2: common.DeploymentStatusMessage.deploymentStatus:type_name -> common.DeploymentStatus
	14, // 3: common.ContainerStateListMessage.data:type_name -> common.ContainerStateItem
	25, // 4: common.ContainerStateItem.id:type_name -> common.ContainerIdentifier
	29, // 5: common.ContainerStateItem.createdAt:type_name -> google.protobuf.Timestamp
	0,  // 6: common.ContainerStateItem.state:type_name -> common.ContainerState
	12, // 7: common.ContainerStateItem.ports:type_name -> common.ContainerStateItemPort
	28, // 8: common.ContainerStateItem.labels:type_name -> common.ContainerStateItem.LabelsEntry
	20, // 9: common.ResourceConfig.limits:type_name -> common.Resource
	20, // 10: common.ResourceConfig.requests:type_name -> common.Resource
	25, // 11: common.ContainerCommandRequest.container:type_name -> common.ContainerIdentifier
	8,  // 12: common.ContainerCommandRequest.operation:type_name -> common.ContainerOperation
	25, // 13: common.DeleteContainersRequest.container:type_name -> common.ContainerIdentifier
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protobuf_proto_common_proto_init() }
func file_protobuf_proto_common_proto_init() {
	if File_protobuf_proto_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstanceDeploymentItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeploymentStatusMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerStateItemPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerStateListMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerStateItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerLogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerInspectMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Routing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSecretsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_common_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteContainersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_proto_common_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*DeploymentStatusMessage_Instance)(nil),
		(*DeploymentStatusMessage_DeploymentStatus)(nil),
	}
	file_protobuf_proto_common_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_protobuf_proto_common_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_protobuf_proto_common_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_protobuf_proto_common_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_protobuf_proto_common_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_protobuf_proto_common_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*DeleteContainersRequest_Container)(nil),
		(*DeleteContainersRequest_Prefix)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_common_proto_rawDesc,
			NumEnums:      9,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_proto_common_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_common_proto_depIdxs,
		EnumInfos:         file_protobuf_proto_common_proto_enumTypes,
		MessageInfos:      file_protobuf_proto_common_proto_msgTypes,
	}.Build()
	File_protobuf_proto_common_proto = out.File
	file_protobuf_proto_common_proto_rawDesc = nil
	file_protobuf_proto_common_proto_goTypes = nil
	file_protobuf_proto_common_proto_depIdxs = nil
}
