#!/bin/bash
set -eu

# Wait for PostgreSQL to start
until pg_isready -U "${POSTGRES_USER}"; do
  echo "Waiting for PostgreSQL to start..."
  sleep 2
done

# Create the database and users dynamically
echo "Creating databases and users..."

psql -v ON_ERROR_STOP=1 --username ${POSTGRES_USER} <<-EOSQL
  CREATE USER ${CRUX_POSTGRES_USER} WITH ENCRYPTED PASSWORD '${CRUX_POSTGRES_PASSWORD}';
  CREATE DATABASE ${CRUX_POSTGRES};
  GRANT ALL PRIVILEGES ON DATABASE ${CRUX_POSTGRES} TO ${CRUX_POSTGRES_USER};
  ALTER DATABASE ${CRUX_POSTGRES} OWNER TO ${CRUX_POSTGRES_USER};

  CREATE USER ${KRATOS_POSTGRES_USER} WITH ENCRYPTED PASSWORD '${KRATOS_POSTGRES_PASSWORD}';
  CREATE DATABASE ${KRATOS_POSTGRES};
  GRANT ALL PRIVILEGES ON DATABASE ${KRATOS_POSTGRES} TO ${KRATOS_POSTGRES_USER};
  ALTER DATABASE ${KRATOS_POSTGRES} OWNER TO ${KRATOS_POSTGRES_USER};
EOSQL

echo "Databases and users created successfully."
