'source:web': 'web'
'source:documentation': 'docs'
'source:agent':
  - 'golang/pkg/crane'
  - 'golang/pkg/dagent'
  - 'golang/cmd/crane'
  - 'golang/cmd/dagent'
'source:ci': '.github/workflows/'
'source:build':
  - '**/Makefile'
  - 'web/kratos'
  - '**/Dockerfile'
  - 'golang/build'
'source:cli':
  - 'golang/pkg/cli'
  - 'golang/cmd/dyo'
'lang:makefile': '**/Makefile'
'lang:shell':
  - '**/*.sh'
  - '**/*.sh.hbr'
  - '**/*.ps1.hbr'
'lang:golang': '**/*.go'
'lang:typescript':
  - '**/*.ts'
  - '**/*.js'
