run:
  timeout: 5m
linters-settings:
  depguard:
    rules:
      logblock:
        deny:
          - pkg: "log"
            desc: "logging is allowed only by github.com/rs/zerolog"
  dupl:
    threshold: 100
  forbidigo:
    exclude-godoc-examples: false
    forbid:
      - ^print.*$
      - 'fmt\.Print.*'
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/golangci/golangci-lint,github.com/dyrector-io/dyrectorio
  govet:
    enable-all: true
  lll:
    line-length: 140
  misspell:
    locale: US
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  tenv:
    all: true
  staticcheck:
    checks:
      - all
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    # TODO(nandor-magyar): refactor golang code to comply
    # - containedctx
    - depguard
    - dogsled
    - durationcheck
    - dupl
    - errcheck
    - errname
    - copyloopvar
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofumpt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - usetesting
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
  exclude-dirs:
    - internal/cache
