version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
  settings:
    depguard:
      rules:
        logblock:
          deny:
            - pkg: log
              desc: logging is allowed only by github.com/rs/zerolog
    dupl:
      threshold: 100
    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: fmt\.Print.*
      exclude-godoc-examples: false
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        path: _test\.go
    paths:
      - internal/cache
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
        - github.com/dyrector-io/dyrectorio
  exclusions:
    generated: lax
    paths:
      - internal/cache
      - third_party$
      - builtin$
      - examples$
