FROM docker.io/library/node:24-alpine3.22

SHELL ["/bin/ash","-c"]
WORKDIR /usr/work
LABEL org.opencontainers.image.source="https://github.com/dyrector-io/dyrectorio/tree/develop/distribution/images/builder-nodejs"

RUN apk add alpine-sdk docker zstd jq

