# Automatically label new pull requests based on the paths of files being changed or the branch name.
source:web: [web/**]
source:documentation: [docs/**]
source:agent:
  - golang/pkg/crane/**
  - golang/pkg/dagent/**
  - golang/cmd/crane/**
  - golang/cmd/dagent/**
source:ci:
  - .github/workflows/**
  - .github/config/**
source:build:
  - '**/Makefile'
  - images/**
  - '**/Dockerfile'
  - golang/build/**
source:kratos: [web/kratos/**]
source:proto: [proto/**, '**/*.proto']
source:cli: [golang/pkg/cli/**, golang/cmd/dyo/**]
lang:makefile: ['**/Makefile']
lang:sql: ['**/*.prisma', '**/*.sql']
lang:shell: ['**/*.sh', '**/*.sh.hbr', '**/*.ps1.hbr']
lang:golang: ['**/*.go']
lang:typescript: ['**/*.ts', '**/*.tsx']
lang:javascript: ['**/*.js', '**/*.jsx']
