version: "3.3"

services:
  kratos-postgres:
    container_name: crux-kratos-postgres
    image: postgres:13.3-alpine3.14
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=kratos
      - POSTGRES_DB=kratos
    restart: unless-stopped
    volumes:
      - kratos-db:/var/lib/postgresql/data
    networks:
      - crux-intranet

  kratos-migrate:
    container_name: crux-kratos-migrate
    image: ghcr.io/dyrector-io/dyrectorio/kratos:${AUTH_VERSION}
    depends_on:
      - kratos-postgres
    environment:
      - SQA_OPT_OUT=true
      - DSN=postgres://kratos:${POSTGRES_PASSWORD}@kratos-postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    command: -c /etc/config/kratos/kratos.yaml migrate sql -e --yes
    volumes:
      - kratos-config:/etc/config/kratos
    networks:
      - crux-intranet

  kratos:
    container_name: crux-kratos
    image: ghcr.io/dyrector-io/dyrectorio/kratos:${AUTH_VERSION}
    build: 
      context: ./config
    depends_on: 
      kratos-migrate:
        condition: service_completed_successfully
    platform: linux/amd64
    ports:
      - 9433:4433 # public
      # To generate a new user, you have to expose the admin port
      # Comment out the next line for this
      - 9434:4434
    environment:
      - SERVE_ADMIN_BASE_URL=${SERVE_ADMIN_BASE_URL}
      - KRATOS_URL=$KRATOS_URL
      - AUTH_URL=$AUTH_URL
      - DEV=${KRATOS_DEV}
      - SQA_OPT_OUT=true
      - DSN=postgres://kratos:${POSTGRES_PASSWORD}@kratos-postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=${KRATOS_LOG_LEVEL}
      - LOG_LEAK_SENSITIVE_VALUES=${KRATOS_LOG_LEAK_SENSITIVE_VALUES}
      - SECRETS_COOKIE=${COOKIE_SECRET}
      - COURIER_SMTP_CONNECTION_URI=smtps://${SMTP_USER}:${SMTP_PASSWORD}@${SMTP_URL}
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yaml --watch-courier
    volumes:
      - kratos-config:/etc/config/kratos
    networks:
      - crux-intranet

volumes:
  kratos-db:
  kratos-config:

networks:
  crux-intranet:
    name: crux-intranet
    external: true