import { ConfigService } from '@nestjs/config'
import { DocumentBuilder, OpenAPIObject } from '@nestjs/swagger'

const createSwaggerConfig = (configService: ConfigService): Omit<OpenAPIObject, 'paths'> =>
  new DocumentBuilder()
    .setTitle('dyrector.io platform API')
    .setDescription('The dyrector.io platform API documentation.')
    .setVersion(configService.get<string>('npm_package_version'))
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'Bearer',
        description: 'Please enter token in following format: ',
      },
      'jwt',
    )
    .addTag(
      'projects',
      'There are two kinds of projects in dyrector.io: Versionless and Versioned. Versionless projects make up one deployable unit without versioning, while Versioned projects come with multiple rolling or incremental versions. More details in dyrector.io platform [documentation](https://docs.dyrector.io/tutorials/create-your-project).',
    )
    .addTag(
      'versions',
      'Versions belong to projects. While Versionless Projects seemingly do not have a version, they act as a rolling version of a Versioned Project.</br></br>The purpose of versions is to separate different variations of your project. They can be either rolling or incremental. One Versioned Project can have multiple versions of both types. More details about rolling and incremental versions in dyrector.io platform [documentation](https://docs.dyrector.io/get-started/components#project).',
    )
    .addTag('version/images', "Images make up a Versioned Project's version, or a Versionless Project.")
    .addTag(
      'registries',
      'Registries are 3rd party registries where the images of versions are located. Learn more about registries in dyrector.io platform [documentation](https://docs.dyrector.io/get-started/components#registry).',
    )
    .addTag(
      'teams',
      'Teams are the shared entity of multiple users. The purpose of teams is to separate users, nodes and projects based on their needs within an organization. Team owners can assign roles. More details about teams in dyrector.io platform [documentation](https://docs.dyrector.io/get-started/components#team).',
    )
    .addTag('users/me', 'users/me cover endpoints related to your user profile.')
    .addTag(
      'deployments',
      'Deployments are the process that gets the installation of your versions or Versionless Projects done on the node of your choice. More details about deployments in dyrector.io platform [documentation](https://docs.dyrector.io/get-started/components#deployment).',
    )
    .addTag(
      'tokens',
      'Tokens are the access tokens that grant you access to a user profile and the teams the profile is a member of.',
    )
    .addTag(
      'nodes',
      'Nodes are the deployment targets. Nodes are registered by installing at least one of the agents - crane for Kubernetes, dagent for Docker. These agents connect the platform to your node. One team can have as many nodes as they like.</br></br>Node installation takes place with Shell or PowerShell scripts, which can be created or revoked. More details in dyrector.io platform [documentation](https://docs.dyrector.io/get-started/components#node).',
    )
    .addTag('audit-log', 'Audit log is a log of team activity generated by the platform.')
    .addTag(
      'health',
      'Health refers to the status of the different services that make up the platform. It can be checked to see if the platform works properly.',
    )
    .addTag(
      'notifications',
      'Notifications are chat notifications in Slack, Discord, and Teams. They send an automated message about deployments, new versions, new nodes, and new users. More details in dyrector.io platform [documentation](https://docs.dyrector.io/tutorials/create-chat-notifications).',
    )
    .addTag(
      'templates',
      'Templates are preset applications that can be turned into a project right away. They can be deployed with minimal configuration. More details about templates in dyrector.io platform [documentation](https://docs.dyrector.io/features/templates).',
    )
    .addTag('dashboard', 'Dashboard summarizes the latest activities of a team.')
    .addTag(
      'storages',
      'Storages are S3 compatible memory storages. They can be used for file injection. More details in dyrector.io platform [documentation](https://docs.dyrector.io/features/storage).',
    )
    .build()

export default createSwaggerConfig
