style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/dyrector-io/dyrectorio
options:
  commits:
    sort_by: Type
  commit_groups:
    title_maps:
  header:
    pattern: "^(ci|fix|feat|chore|doc|docs|style|techdebt|refactor|perf|build)(\\(web\\)|\\(agent\\)|\\(crux\\)|\\(crux-ui\\)|\\(ci\\)|\\(cli\\))?\\:\\s?([\\S ]*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
