//*
// Container agent interface messages and service definitions
// Logs, statuses, deployments
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: protobuf/proto/agent.proto

package agent

import (
	crux "github.com/dyrector-io/dyrectorio/protobuf/go/crux"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployRequest_ContainerConfig_RuntimeConfigType int32

const (
	// appconfig will be parsed into environment variables
	DeployRequest_ContainerConfig_DOTNET_APPCONFIG DeployRequest_ContainerConfig_RuntimeConfigType = 0
)

// Enum value maps for DeployRequest_ContainerConfig_RuntimeConfigType.
var (
	DeployRequest_ContainerConfig_RuntimeConfigType_name = map[int32]string{
		0: "DOTNET_APPCONFIG",
	}
	DeployRequest_ContainerConfig_RuntimeConfigType_value = map[string]int32{
		"DOTNET_APPCONFIG": 0,
	}
)

func (x DeployRequest_ContainerConfig_RuntimeConfigType) Enum() *DeployRequest_ContainerConfig_RuntimeConfigType {
	p := new(DeployRequest_ContainerConfig_RuntimeConfigType)
	*p = x
	return p
}

func (x DeployRequest_ContainerConfig_RuntimeConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployRequest_ContainerConfig_RuntimeConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_agent_proto_enumTypes[0].Descriptor()
}

func (DeployRequest_ContainerConfig_RuntimeConfigType) Type() protoreflect.EnumType {
	return &file_protobuf_proto_agent_proto_enumTypes[0]
}

func (x DeployRequest_ContainerConfig_RuntimeConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployRequest_ContainerConfig_RuntimeConfigType.Descriptor instead.
func (DeployRequest_ContainerConfig_RuntimeConfigType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{5, 1, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{0}
}

//*
//
//
type AgentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AgentCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//	*AgentCommand_Deploy
	//	*AgentCommand_ContainerStatus
	//	*AgentCommand_ContainerDelete
	Command isAgentCommand_Command `protobuf_oneof:"command"`
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (m *AgentCommand) GetCommand() isAgentCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *AgentCommand) GetDeploy() *VersionDeployRequest {
	if x, ok := x.GetCommand().(*AgentCommand_Deploy); ok {
		return x.Deploy
	}
	return nil
}

func (x *AgentCommand) GetContainerStatus() *ContainerStatusRequest {
	if x, ok := x.GetCommand().(*AgentCommand_ContainerStatus); ok {
		return x.ContainerStatus
	}
	return nil
}

func (x *AgentCommand) GetContainerDelete() *ContainerDeleteRequest {
	if x, ok := x.GetCommand().(*AgentCommand_ContainerDelete); ok {
		return x.ContainerDelete
	}
	return nil
}

type isAgentCommand_Command interface {
	isAgentCommand_Command()
}

type AgentCommand_Deploy struct {
	Deploy *VersionDeployRequest `protobuf:"bytes,1,opt,name=deploy,proto3,oneof"`
}

type AgentCommand_ContainerStatus struct {
	ContainerStatus *ContainerStatusRequest `protobuf:"bytes,2,opt,name=containerStatus,proto3,oneof"`
}

type AgentCommand_ContainerDelete struct {
	ContainerDelete *ContainerDeleteRequest `protobuf:"bytes,3,opt,name=containerDelete,proto3,oneof"`
}

func (*AgentCommand_Deploy) isAgentCommand_Command() {}

func (*AgentCommand_ContainerStatus) isAgentCommand_Command() {}

func (*AgentCommand_ContainerDelete) isAgentCommand_Command() {}

//*
// This is more of a placeholder, we could include more, or return this
// instantly after validation success.
type DeployResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Started bool `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DeployResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

type VersionDeployRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VersionName  string           `protobuf:"bytes,2,opt,name=versionName,proto3" json:"versionName,omitempty"`
	ReleaseNotes string           `protobuf:"bytes,3,opt,name=releaseNotes,proto3" json:"releaseNotes,omitempty"`
	Requests     []*DeployRequest `protobuf:"bytes,4,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *VersionDeployRequest) Reset() {
	*x = VersionDeployRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionDeployRequest) ProtoMessage() {}

func (x *VersionDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionDeployRequest.ProtoReflect.Descriptor instead.
func (*VersionDeployRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *VersionDeployRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VersionDeployRequest) GetVersionName() string {
	if x != nil {
		return x.VersionName
	}
	return ""
}

func (x *VersionDeployRequest) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

func (x *VersionDeployRequest) GetRequests() []*DeployRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

//*
// Deploys a single container
//
type DeployRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// InstanceConfig is set for multiple containers
	InstanceConfig *DeployRequest_InstanceConfig `protobuf:"bytes,2,opt,name=instanceConfig,proto3" json:"instanceConfig,omitempty"`
	// Runtime info and requirements of a container
	ContainerConfig *DeployRequest_ContainerConfig `protobuf:"bytes,3,opt,name=containerConfig,proto3" json:"containerConfig,omitempty"`
	RuntimeConfig   *string                        `protobuf:"bytes,4,opt,name=runtimeConfig,proto3,oneof" json:"runtimeConfig,omitempty"`
	Registry        *string                        `protobuf:"bytes,5,opt,name=registry,proto3,oneof" json:"registry,omitempty"`
	ImageName       string                         `protobuf:"bytes,6,opt,name=imageName,proto3" json:"imageName,omitempty"`
	Tag             string                         `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
	RegistryAuth    *DeployRequest_RegistryAuth    `protobuf:"bytes,8,opt,name=registryAuth,proto3,oneof" json:"registryAuth,omitempty"`
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *DeployRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeployRequest) GetInstanceConfig() *DeployRequest_InstanceConfig {
	if x != nil {
		return x.InstanceConfig
	}
	return nil
}

func (x *DeployRequest) GetContainerConfig() *DeployRequest_ContainerConfig {
	if x != nil {
		return x.ContainerConfig
	}
	return nil
}

func (x *DeployRequest) GetRuntimeConfig() string {
	if x != nil && x.RuntimeConfig != nil {
		return *x.RuntimeConfig
	}
	return ""
}

func (x *DeployRequest) GetRegistry() string {
	if x != nil && x.Registry != nil {
		return *x.Registry
	}
	return ""
}

func (x *DeployRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *DeployRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *DeployRequest) GetRegistryAuth() *DeployRequest_RegistryAuth {
	if x != nil {
		return x.RegistryAuth
	}
	return nil
}

type ContainerStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix  *string `protobuf:"bytes,1,opt,name=prefix,proto3,oneof" json:"prefix,omitempty"`
	OneShot *bool   `protobuf:"varint,2,opt,name=oneShot,proto3,oneof" json:"oneShot,omitempty"`
}

func (x *ContainerStatusRequest) Reset() {
	*x = ContainerStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatusRequest) ProtoMessage() {}

func (x *ContainerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatusRequest.ProtoReflect.Descriptor instead.
func (*ContainerStatusRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerStatusRequest) GetPrefix() string {
	if x != nil && x.Prefix != nil {
		return *x.Prefix
	}
	return ""
}

func (x *ContainerStatusRequest) GetOneShot() bool {
	if x != nil && x.OneShot != nil {
		return *x.OneShot
	}
	return false
}

type ContainerDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreName string `protobuf:"bytes,1,opt,name=preName,proto3" json:"preName,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ContainerDeleteRequest) Reset() {
	*x = ContainerDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerDeleteRequest) ProtoMessage() {}

func (x *ContainerDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerDeleteRequest.ProtoReflect.Descriptor instead.
func (*ContainerDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerDeleteRequest) GetPreName() string {
	if x != nil {
		return x.PreName
	}
	return ""
}

func (x *ContainerDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeployRequest_InstanceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	//containerPreName, mapped into host folder structure,
	//used as namespace id
	Prefix           string                                    `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	MountPath        *string                                   `protobuf:"bytes,2,opt,name=mountPath,proto3,oneof" json:"mountPath,omitempty"`               // mount path of instance (docker only)
	Environment      *DeployRequest_InstanceConfig_Environment `protobuf:"bytes,3,opt,name=environment,proto3,oneof" json:"environment,omitempty"`           // environment variable map (piped)
	RepositoryPrefix *string                                   `protobuf:"bytes,4,opt,name=repositoryPrefix,proto3,oneof" json:"repositoryPrefix,omitempty"` // registry repo prefix
}

func (x *DeployRequest_InstanceConfig) Reset() {
	*x = DeployRequest_InstanceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployRequest_InstanceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest_InstanceConfig) ProtoMessage() {}

func (x *DeployRequest_InstanceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest_InstanceConfig.ProtoReflect.Descriptor instead.
func (*DeployRequest_InstanceConfig) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DeployRequest_InstanceConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *DeployRequest_InstanceConfig) GetMountPath() string {
	if x != nil && x.MountPath != nil {
		return *x.MountPath
	}
	return ""
}

func (x *DeployRequest_InstanceConfig) GetEnvironment() *DeployRequest_InstanceConfig_Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *DeployRequest_InstanceConfig) GetRepositoryPrefix() string {
	if x != nil && x.RepositoryPrefix != nil {
		return *x.RepositoryPrefix
	}
	return ""
}

type DeployRequest_ContainerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Container name - must have, used by everthing
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Container prefix
	Prefix *string `protobuf:"bytes,2,opt,name=prefix,proto3,oneof" json:"prefix,omitempty"`
	// container ports
	Ports []*DeployRequest_ContainerConfig_Port `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	// volume mounts in a piped format
	Mounts []string `protobuf:"bytes,4,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// environment variables in a piped format
	Environments []string `protobuf:"bytes,5,rep,name=environments,proto3" json:"environments,omitempty"`
	// could be enum, i'm not sure if it is in use
	NetworkMode *string `protobuf:"bytes,6,opt,name=networkMode,proto3,oneof" json:"networkMode,omitempty"`
	// runtime config type if given, magic can happen
	RuntimeConfigType *DeployRequest_ContainerConfig_RuntimeConfigType `protobuf:"varint,7,opt,name=runtimeConfigType,proto3,enum=agent.DeployRequest_ContainerConfig_RuntimeConfigType,oneof" json:"runtimeConfigType,omitempty"`
	// exposure configuration
	Expose *DeployRequest_ContainerConfig_Expose `protobuf:"bytes,8,opt,name=expose,proto3,oneof" json:"expose,omitempty"`
	// Config container is started before the container and contents are copied
	// to the volume set
	ConfigContainer *DeployRequest_ContainerConfig_ConfigContainer `protobuf:"bytes,9,opt,name=configContainer,proto3,oneof" json:"configContainer,omitempty"`
	// userId that is used to run the container, number
	User int64 `protobuf:"varint,10,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *DeployRequest_ContainerConfig) Reset() {
	*x = DeployRequest_ContainerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployRequest_ContainerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest_ContainerConfig) ProtoMessage() {}

func (x *DeployRequest_ContainerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest_ContainerConfig.ProtoReflect.Descriptor instead.
func (*DeployRequest_ContainerConfig) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{5, 1}
}

func (x *DeployRequest_ContainerConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployRequest_ContainerConfig) GetPrefix() string {
	if x != nil && x.Prefix != nil {
		return *x.Prefix
	}
	return ""
}

func (x *DeployRequest_ContainerConfig) GetPorts() []*DeployRequest_ContainerConfig_Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *DeployRequest_ContainerConfig) GetMounts() []string {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *DeployRequest_ContainerConfig) GetEnvironments() []string {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *DeployRequest_ContainerConfig) GetNetworkMode() string {
	if x != nil && x.NetworkMode != nil {
		return *x.NetworkMode
	}
	return ""
}

func (x *DeployRequest_ContainerConfig) GetRuntimeConfigType() DeployRequest_ContainerConfig_RuntimeConfigType {
	if x != nil && x.RuntimeConfigType != nil {
		return *x.RuntimeConfigType
	}
	return DeployRequest_ContainerConfig_DOTNET_APPCONFIG
}

func (x *DeployRequest_ContainerConfig) GetExpose() *DeployRequest_ContainerConfig_Expose {
	if x != nil {
		return x.Expose
	}
	return nil
}

func (x *DeployRequest_ContainerConfig) GetConfigContainer() *DeployRequest_ContainerConfig_ConfigContainer {
	if x != nil {
		return x.ConfigContainer
	}
	return nil
}

func (x *DeployRequest_ContainerConfig) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

type DeployRequest_RegistryAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url      string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	User     string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *DeployRequest_RegistryAuth) Reset() {
	*x = DeployRequest_RegistryAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployRequest_RegistryAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest_RegistryAuth) ProtoMessage() {}

func (x *DeployRequest_RegistryAuth) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest_RegistryAuth.ProtoReflect.Descriptor instead.
func (*DeployRequest_RegistryAuth) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{5, 2}
}

func (x *DeployRequest_RegistryAuth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployRequest_RegistryAuth) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DeployRequest_RegistryAuth) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DeployRequest_RegistryAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeployRequest_InstanceConfig_Environment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Env []string `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty"`
}

func (x *DeployRequest_InstanceConfig_Environment) Reset() {
	*x = DeployRequest_InstanceConfig_Environment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployRequest_InstanceConfig_Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest_InstanceConfig_Environment) ProtoMessage() {}

func (x *DeployRequest_InstanceConfig_Environment) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest_InstanceConfig_Environment.ProtoReflect.Descriptor instead.
func (*DeployRequest_InstanceConfig_Environment) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *DeployRequest_InstanceConfig_Environment) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type DeployRequest_ContainerConfig_Port struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Internal int32 `protobuf:"varint,1,opt,name=internal,proto3" json:"internal,omitempty"` // internal that is bound by the container
	External int32 `protobuf:"varint,3,opt,name=external,proto3" json:"external,omitempty"` // external is docker only
}

func (x *DeployRequest_ContainerConfig_Port) Reset() {
	*x = DeployRequest_ContainerConfig_Port{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployRequest_ContainerConfig_Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest_ContainerConfig_Port) ProtoMessage() {}

func (x *DeployRequest_ContainerConfig_Port) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest_ContainerConfig_Port.ProtoReflect.Descriptor instead.
func (*DeployRequest_ContainerConfig_Port) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{5, 1, 0}
}

func (x *DeployRequest_ContainerConfig_Port) GetInternal() int32 {
	if x != nil {
		return x.Internal
	}
	return 0
}

func (x *DeployRequest_ContainerConfig_Port) GetExternal() int32 {
	if x != nil {
		return x.External
	}
	return 0
}

type DeployRequest_ContainerConfig_Expose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Public bool `protobuf:"varint,1,opt,name=public,proto3" json:"public,omitempty"` // if expose is needed
	Tls    bool `protobuf:"varint,2,opt,name=tls,proto3" json:"tls,omitempty"`       // if tls is needed
}

func (x *DeployRequest_ContainerConfig_Expose) Reset() {
	*x = DeployRequest_ContainerConfig_Expose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployRequest_ContainerConfig_Expose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest_ContainerConfig_Expose) ProtoMessage() {}

func (x *DeployRequest_ContainerConfig_Expose) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest_ContainerConfig_Expose.ProtoReflect.Descriptor instead.
func (*DeployRequest_ContainerConfig_Expose) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{5, 1, 1}
}

func (x *DeployRequest_ContainerConfig_Expose) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *DeployRequest_ContainerConfig_Expose) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

type DeployRequest_ContainerConfig_ConfigContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image     string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Volume    string `protobuf:"bytes,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Path      string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	KeepFiles bool   `protobuf:"varint,4,opt,name=keepFiles,proto3" json:"keepFiles,omitempty"`
}

func (x *DeployRequest_ContainerConfig_ConfigContainer) Reset() {
	*x = DeployRequest_ContainerConfig_ConfigContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_agent_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployRequest_ContainerConfig_ConfigContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest_ContainerConfig_ConfigContainer) ProtoMessage() {}

func (x *DeployRequest_ContainerConfig_ConfigContainer) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_agent_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest_ContainerConfig_ConfigContainer.ProtoReflect.Descriptor instead.
func (*DeployRequest_ContainerConfig_ConfigContainer) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_agent_proto_rawDescGZIP(), []int{5, 1, 2}
}

func (x *DeployRequest_ContainerConfig_ConfigContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeployRequest_ContainerConfig_ConfigContainer) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *DeployRequest_ContainerConfig_ConfigContainer) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeployRequest_ContainerConfig_ConfigContainer) GetKeepFiles() bool {
	if x != nil {
		return x.KeepFiles
	}
	return false
}

var File_protobuf_proto_agent_proto protoreflect.FileDescriptor

var file_protobuf_proto_agent_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x75, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x35, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xe6,
	0x01, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x35, 0x0a, 0x06, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x49, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x49, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x22, 0x9e, 0x01, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4e, 0x6f, 0x74,
	0x65, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x22, 0xbe, 0x0d, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4b, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x4e, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x29, 0x0a, 0x0d, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x88, 0x01, 0x01, 0x12, 0x1f,
	0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x88, 0x01, 0x01, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x4a, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x41, 0x75, 0x74, 0x68, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x41, 0x75, 0x74, 0x68, 0x48, 0x02, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x41, 0x75, 0x74, 0x68, 0x88, 0x01, 0x01, 0x1a, 0xa8, 0x02, 0x0a, 0x0e,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x21, 0x0a, 0x09, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12, 0x56, 0x0a, 0x0b, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x48,
	0x01, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x88, 0x01,
	0x01, 0x12, 0x2f, 0x0a, 0x10, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x50,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x10, 0x72,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x88,
	0x01, 0x01, 0x1a, 0x1f, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x6e, 0x76, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x1a, 0xf6, 0x06, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x88, 0x01, 0x01, 0x12, 0x3f, 0x0a, 0x05, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x0b, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x69, 0x0a, 0x11, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x36, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x48, 0x02, 0x52, 0x11, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x48, 0x0a, 0x06, 0x65, 0x78,
	0x70, 0x6f, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x48, 0x03, 0x52, 0x06, 0x65, 0x78, 0x70, 0x6f, 0x73,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x63, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x48, 0x04, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x3e, 0x0a,
	0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x1a, 0x32, 0x0a,
	0x06, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x74, 0x6c,
	0x73, 0x1a, 0x71, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x11, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x4f, 0x54,
	0x4e, 0x45, 0x54, 0x5f, 0x41, 0x50, 0x50, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0x00, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x42, 0x12, 0x0a, 0x10, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x1a,
	0x64, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x41, 0x75, 0x74, 0x68, 0x22, 0x6b, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07,
	0x6f, 0x6e, 0x65, 0x53, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52,
	0x07, 0x6f, 0x6e, 0x65, 0x53, 0x68, 0x6f, 0x74, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x6e, 0x65, 0x53, 0x68,
	0x6f, 0x74, 0x22, 0x46, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xc3, 0x01, 0x0a, 0x05, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12,
	0x10, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x13, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x30, 0x01, 0x12, 0x41, 0x0a, 0x10, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x2e, 0x63,
	0x72, 0x75, 0x78, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0c, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x12, 0x43, 0x0a, 0x0f, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20,
	0x2e, 0x63, 0x72, 0x75, 0x78, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x0c, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x79, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x69, 0x6f, 0x2f, 0x64, 0x79, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x69, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67,
	0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_proto_agent_proto_rawDescOnce sync.Once
	file_protobuf_proto_agent_proto_rawDescData = file_protobuf_proto_agent_proto_rawDesc
)

func file_protobuf_proto_agent_proto_rawDescGZIP() []byte {
	file_protobuf_proto_agent_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_agent_proto_rawDescData)
	})
	return file_protobuf_proto_agent_proto_rawDescData
}

var file_protobuf_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protobuf_proto_agent_proto_goTypes = []interface{}{
	(DeployRequest_ContainerConfig_RuntimeConfigType)(0), // 0: agent.DeployRequest.ContainerConfig.RuntimeConfigType
	(*Empty)(nil),                                         // 1: agent.Empty
	(*AgentInfo)(nil),                                     // 2: agent.AgentInfo
	(*AgentCommand)(nil),                                  // 3: agent.AgentCommand
	(*DeployResponse)(nil),                                // 4: agent.DeployResponse
	(*VersionDeployRequest)(nil),                          // 5: agent.VersionDeployRequest
	(*DeployRequest)(nil),                                 // 6: agent.DeployRequest
	(*ContainerStatusRequest)(nil),                        // 7: agent.ContainerStatusRequest
	(*ContainerDeleteRequest)(nil),                        // 8: agent.ContainerDeleteRequest
	(*DeployRequest_InstanceConfig)(nil),                  // 9: agent.DeployRequest.InstanceConfig
	(*DeployRequest_ContainerConfig)(nil),                 // 10: agent.DeployRequest.ContainerConfig
	(*DeployRequest_RegistryAuth)(nil),                    // 11: agent.DeployRequest.RegistryAuth
	(*DeployRequest_InstanceConfig_Environment)(nil),      // 12: agent.DeployRequest.InstanceConfig.Environment
	(*DeployRequest_ContainerConfig_Port)(nil),            // 13: agent.DeployRequest.ContainerConfig.Port
	(*DeployRequest_ContainerConfig_Expose)(nil),          // 14: agent.DeployRequest.ContainerConfig.Expose
	(*DeployRequest_ContainerConfig_ConfigContainer)(nil), // 15: agent.DeployRequest.ContainerConfig.ConfigContainer
	(*crux.DeploymentStatusMessage)(nil),                  // 16: crux.DeploymentStatusMessage
	(*crux.ContainerStatusListMessage)(nil),               // 17: crux.ContainerStatusListMessage
}
var file_protobuf_proto_agent_proto_depIdxs = []int32{
	5,  // 0: agent.AgentCommand.deploy:type_name -> agent.VersionDeployRequest
	7,  // 1: agent.AgentCommand.containerStatus:type_name -> agent.ContainerStatusRequest
	8,  // 2: agent.AgentCommand.containerDelete:type_name -> agent.ContainerDeleteRequest
	6,  // 3: agent.VersionDeployRequest.requests:type_name -> agent.DeployRequest
	9,  // 4: agent.DeployRequest.instanceConfig:type_name -> agent.DeployRequest.InstanceConfig
	10, // 5: agent.DeployRequest.containerConfig:type_name -> agent.DeployRequest.ContainerConfig
	11, // 6: agent.DeployRequest.registryAuth:type_name -> agent.DeployRequest.RegistryAuth
	12, // 7: agent.DeployRequest.InstanceConfig.environment:type_name -> agent.DeployRequest.InstanceConfig.Environment
	13, // 8: agent.DeployRequest.ContainerConfig.ports:type_name -> agent.DeployRequest.ContainerConfig.Port
	0,  // 9: agent.DeployRequest.ContainerConfig.runtimeConfigType:type_name -> agent.DeployRequest.ContainerConfig.RuntimeConfigType
	14, // 10: agent.DeployRequest.ContainerConfig.expose:type_name -> agent.DeployRequest.ContainerConfig.Expose
	15, // 11: agent.DeployRequest.ContainerConfig.configContainer:type_name -> agent.DeployRequest.ContainerConfig.ConfigContainer
	2,  // 12: agent.Agent.Connect:input_type -> agent.AgentInfo
	16, // 13: agent.Agent.DeploymentStatus:input_type -> crux.DeploymentStatusMessage
	17, // 14: agent.Agent.ContainerStatus:input_type -> crux.ContainerStatusListMessage
	3,  // 15: agent.Agent.Connect:output_type -> agent.AgentCommand
	1,  // 16: agent.Agent.DeploymentStatus:output_type -> agent.Empty
	1,  // 17: agent.Agent.ContainerStatus:output_type -> agent.Empty
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_protobuf_proto_agent_proto_init() }
func file_protobuf_proto_agent_proto_init() {
	if File_protobuf_proto_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionDeployRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployRequest_InstanceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployRequest_ContainerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployRequest_RegistryAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployRequest_InstanceConfig_Environment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployRequest_ContainerConfig_Port); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployRequest_ContainerConfig_Expose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_agent_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployRequest_ContainerConfig_ConfigContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_proto_agent_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*AgentCommand_Deploy)(nil),
		(*AgentCommand_ContainerStatus)(nil),
		(*AgentCommand_ContainerDelete)(nil),
	}
	file_protobuf_proto_agent_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_protobuf_proto_agent_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_protobuf_proto_agent_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_protobuf_proto_agent_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_agent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_proto_agent_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_agent_proto_depIdxs,
		EnumInfos:         file_protobuf_proto_agent_proto_enumTypes,
		MessageInfos:      file_protobuf_proto_agent_proto_msgTypes,
	}.Build()
	File_protobuf_proto_agent_proto = out.File
	file_protobuf_proto_agent_proto_rawDesc = nil
	file_protobuf_proto_agent_proto_goTypes = nil
	file_protobuf_proto_agent_proto_depIdxs = nil
}
