import { ConfigService } from '@nestjs/config'
import { DocumentBuilder, OpenAPIObject } from '@nestjs/swagger'

const createSwaggerConfig = (configService: ConfigService): Omit<OpenAPIObject, 'paths'> => {
  const config = new DocumentBuilder()
    .setTitle('dyrectorio platform API')
    .setDescription('The dyrectorio platform API documentation.')
    .setVersion(configService.get<string>('npm_package_version'))
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'Bearer',
        description: 'Please enter token in following format: ',
      },
      'jwt',
    )
    .addTag(
      'products',
      'There are two kinds of products in dyrectorio: Simple and Complex. Simple products make up one deployable unit without versioning, while Complex products come with multiple rolling or incremental versions. More details in dyrectorio platform [documentation](https://docs.dyrector.io/tutorials/create-your-product).',
    )
    .addTag(
      'versions',
      'Versions belong to products. While Simple Products are technically versionless, they act as a rolling version of a Complex Product.</br></br>The purpose of versions is to separate different variations of your product. They can be either rolling or incremental. One Complex Product can have multiple versions of both types. More details about rolling and incremental versions in dyrectorio platform [documentation](https://docs.dyrector.io/get-started/components#product).',
    )
    .addTag('version/images', "Images make up a Complex Product's version, or a Simple Product.")
    .addTag(
      'registries',
      'Registries are 3rd party registries where the images of versions are located. Learn more about registries in dyrectorio platform [documentation](https://docs.dyrector.io/get-started/components#registry).',
    )
    .addTag(
      'teams',
      'Teams are the shared entity of multiple users. The purpose of teams is to separate users, nodes and products based on their needs within an organization. Team owners can assign roles. More details about teams in dyrectorio platform [documentation](https://docs.dyrector.io/get-started/components#team).',
    )
    .addTag('users/me', 'users/me cover endpoints related to your user profile.')
    .addTag(
      'deployments',
      'Deployments are the process that gets the installation of your versions or Simple Products done on the node of your choice. More details about deployments in dyrectorio platform [documentation](https://docs.dyrector.io/get-started/components#deployment).',
    )
    .addTag(
      'tokens',
      'Tokens are the access tokens that grant you access to a user profile and the teams the profile is a member of.',
    )
    .addTag(
      'nodes',
      'Nodes are the deployment targets. Nodes are registered by installing at least one of the agents - crane for Kubernetes, dagent for Docker. These agents connect the platform to your node. One team can have as many nodes as they like.</br></br>Node installation takes place with Shell or PowerShell scripts, which can be created or revoked. More details in dyrectorio platform [documentation](https://docs.dyrector.io/get-started/components#node).',
    )
    .addTag('audit-log', 'Audit log is a log of team activity generated by the platform.')
    .addTag(
      'health',
      'Health refers to the status of the different services that make up the platform. It can be checked to see if the platform works properly.',
    )
    .addTag(
      'notifications',
      'Notifications are chat notifications in Slack, Discord, and Teams. They send an automated message about deployments, new versions, new nodes, and new users. More details in dyrectorio platform [documentation](https://docs.dyrector.io/tutorials/create-chat-notifications).',
    )
    .addTag(
      'templates',
      'Templates are preset applications that can be turned into a product right away. They can be deployed with minimal configuration. More details about templates in dyrectorio platform [documentation](https://docs.dyrector.io/features/templates).',
    )
    .addTag('dashboard', 'Dashboard summarizes the latest activities of a team.')
    .addTag(
      'storages',
      'Storages are S3 compatible memory storages. They can be used for file injection. More details in dyrectorio platform [documentation](https://docs.dyrector.io/features/storage).',
    )

  return config.build()
}

export default createSwaggerConfig
