name: agent
on: 
  push:
    paths:
      - agent/**
      - .github/workflows/agent.yml

permissions:
  contents: read
  pull-requests: read
  packages: write


env:
  # Environments
  GOFLAGS: "-buildvcs=false"

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dyrector-io/dyrectorio/alpine-proto:3.16
    defaults:
      run:
        working-directory: agent
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Load go mod
      run: go mod tidy
    - name: Run golangci-lint
      run: pwd && make lint
  security:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dyrector-io/dyrectorio/alpine-proto:3.16
    defaults:
      run:
        working-directory: agent
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Load go mod
      run: go mod tidy
    - name: Run gosec
      run: make security
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dyrector-io/dyrectorio/alpine-proto:3.16
    defaults:
      run:
        working-directory: agent
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3

      # fixes: fatal: unsafe repository 
      - name: Adding workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Load go mod
        run: go mod tidy

      - name: Compile
        run: make compile-both
      

      - name: Docker build with latest tag
        run: make image_version=test bbpb

      - name: Docker build with latest tag
        if: github.ref == 'refs/heads/develop'
        run: make image_version=latest bbpb

      - name: Docker build with stable tag
        if: github.ref == 'refs/heads/main'
        run: make image_version=stable bbpb