name: agent
on: 
  push:
    paths:
      - agent/**
      - .github/workflows/agent.yml

permissions:
  contents: read
  pull-requests: read
  packages: read

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dyrector-io/dyrectorio/alpine-proto:3.16
    defaults:
      run:
        working-directory: agent
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: test
      run: pwd && ls -lah
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.46
        working-directory: agent

  security:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dyrector-io/dyrectorio/alpine-proto:3.16
    defaults:
      run:
        working-directory: agent
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Load go mod
      run: go mod tidy
    - name: Run gosec
      run: make security
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dyrector-io/dyrectorio/alpine-proto:3.16
    defaults:
      run:
        working-directory: agent
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build crane
      run: go build cmd/crane/crane.go 
      
    - name: Build dagent
      run: go build cmd/dagent/dagent.go 
