name: cli
on:
  push:
    paths:
      - cli/**
      - .github/workflows/cli.yml
  pull_request:
    paths:
      - cli/**
      - .github/workflows/cli.yml

permissions:
  contents: read
  pull-requests: read
  packages: write

env:
  # Environments
  GOFLAGS: "-buildvcs=false"

jobs:

  lint:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/dyrector-io/dyrectorio/alpine-proto:3.16
    defaults:
      run:
        working-directory: cli
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Load go mod
      run: go mod tidy
    - name: Run golangci-lint
      run: make lint

  security:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/dyrector-io/dyrectorio/alpine-proto:3.16
    defaults:
      run:
        working-directory: cli
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Load go mod
      run: go mod tidy
    - name: Run gosec
      run: make security
