# workflow containing webhooks that are external to us
name: deploy_external
on:
  workflow_run:
    workflows:
      - 'product_builder'
    branches:
      - 'develop'
    types:
      - completed
permissions:
  contents: read
  pull-requests: read
  actions: read
jobs:
  execute-webhook:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Execute dedicated Sunilium instance webhook
        run: |
          if curl -s -X POST --fail --head 'Authorization: Bearer ${{secrets.SUN_DYO_WEBHOOK_TOKEN}}' ${{secrets.SUN_DYO_WEBHOOK_API_URL}}; then
            echo "Deployment successful."
          else
            exit 1
          fi
