name: builder image

on:
  push:
    branches:
      - develop
    paths: 
      - images/proto/**
      - .github/workflows/image-builder.yml

permissions:
  contents: read
  pull-requests: read
  packages: write

env:
  REGISTRY: ghcr.io
  BUILDER_IMAGE_NAME: dyrector-io/dyrectorio/images/proto
  VERSION: 3.16-5

jobs:
  build_push:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/dyrector-io/dyrectorio/alpine-proto:3.16-4
    defaults:
      run:
        working-directory: images/proto
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t ${REGISTRY}/${BUILDER_IMAGE_NAME}:${VERSION} .
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Docker push
        run: docker push ${REGISTRY}/${BUILDER_IMAGE_NAME}:${VERSION}
      - name: Sign container image
        run: |
          cosign sign --key cosign.key ${REGISTRY}/${BUILDER_IMAGE_NAME}:${VERSION}
        env:
          COSIGN_PASSWORD: "${{ secrets.COSIGN_PASSWORD }}"
