name: "Pull Request Labeler"
on:
  pull_request:

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/labeler@v4
      with:
        configuration-path: .github/labeler.yml

