name: prerequirements

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches:
      - develop

jobs:
  conventional:
    name: Conventional commits validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Run validation
        uses: beemojs/conventional-pr-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-preset: conventionalcommits
