name: deploy
on: push
  # workflow_run:
  #   workflows:
  #     - "product_builder_pipeline"
  #   branches:
  #     - "develop"
  #   types:
  #     - completed
permissions:
  contents: read
  pull-requests: read
  packages: read
  id-token: write
  actions: read
jobs:
 crux_deploy:
    runs-on: ubuntu-22.04
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # environment: staging
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.24'
      - name: Login into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set kubectl context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}'
          cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'
      - name: Rollout restart
        run: |
          kubectl -n dyo-staging rollout restart crux-api
