name: deploy
on:
  workflow_run:
    workflows:
      - "product_builder_pipeline"
    branches:
      - "develop"
    types:
      - completed
permissions:
  contents: read
  pull-requests: read
  actions: read
jobs:
  restart_deployments:
    runs-on: ubuntu-22.04
    container:
      image: bitnami/kubectl:1.26
    steps:
      - name: Rollout restart
        run: |
          echo "${{secrets.AKS_STAGING_CICD_KUBECONFIG}}" > /tmp/kubeconfig
          kubectl --kubeconfig=/tmp/kubeconfig -n dyo-staging rollout restart deployment crux-api crux-kratos crux-ui
