name: web-auth
on: 
  push:
    paths:
      - web/kratos/**
      - .github/workflows/web-kratos.yml

permissions:
  contents: read
  pull-requests: read

jobs:
  Build:
    runs-on: ubuntu-latest
    container: docker:latest
    if: github.ref_name == 'develop' || github.ref_name == 'main'
    defaults:
      run:
        working-directory: web/kratos
    steps:
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker build and push
      run: |
        docker build . -t ghcr.io/dyrector-io/dyrectorio/web-kratos:$IMAGE_TAG
        docker push ghcr.io/dyrector-io/dyrectorio/web-kratos:$IMAGE_TAG
      env:
        IMAGE_TAG: ${{ needs.prerequirements.outputs.tag }}