name: web-auth
on: 
  push:
    paths:
      - web/kratos/**
      - .github/workflows/web-kratos.yml

permissions:
  contents: read
  pull-requests: read

jobs:
  prerequirements:
    runs-on: ubuntu-20.04
    container:
      image: docker:latest
    outputs:
      tag: ${{ steps.settag.outputs.tag }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Setting a buildtag
      id: settag
      working-directory: .github/workflows
      run: ./pipeline_set_output_tag.sh

  build:
    runs-on: ubuntu-20.04
    container: docker:latest
    if: github.ref_name == 'develop' || github.ref_name == 'main'
    defaults:
      run:
        working-directory: web/kratos
    steps:
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker build and push
      run: |
        docker build . -t ghcr.io/dyrector-io/dyrectorio/web-kratos:$IMAGE_TAG
        docker push ghcr.io/dyrector-io/dyrectorio/web-kratos:$IMAGE_TAG
      env:
        IMAGE_TAG: ${{ needs.prerequirements.outputs.tag }}