log:
  level: DEBUG
http:
  routers:
    crux-ui:
      rule: Host(`{{ env "TRAEFIK_HOST" }}`)
      service: crux-ui
      entryPoints:
        - web
    crux:
      rule: Host(`{{ env "TRAEFIK_HOST" }}`) && PathPrefix(`/api`) && !PathPrefix(`/api/auth`) && !PathPrefix(`/api/status`)
      service: crux
      entryPoints:
        - web
  services:
    crux-ui:
      loadBalancer:
        servers:
          - url: http://{{ env "TRAEFIK_HOST" }}:3000/
    crux:
      loadBalancer:
        servers:
          - url: http://{{ env "TRAEFIK_HOST" }}:1848/
