log:
  level: DEBUG

http:
  routers:
    crux-ui:
      rule: Host(`{{ env "TRAEFIK_HOST" }}`)
      service: crux-ui
      entryPoints:
        - web
    crux:
      rule: Host(`{{ env "TRAEFIK_HOST" }}`) && PathPrefix(`/api/new`)
      service: crux
      entryPoints:
        - web
      middlewares:
        - crux-strip-prefix

  middlewares:
    crux-strip-prefix:
      stripprefix:
        prefixes: /api/new

  services:
    crux-ui:
      loadBalancer:
        servers:
          - url: http://{{ env "TRAEFIK_HOST" }}:3000/

    crux:
      loadBalancer:
        servers:
          - url: http://{{ env "TRAEFIK_HOST" }}:1848/
